# .testcoverage.yml
profile: coverage.out

threshold:
  file: 65
  package: 80
  total: 95

exclude:
  paths:
    - ^cmd/
    - \.pb\.go$
    - _mock\.go$

override:
  - threshold: 90
    path: ^internal/agent